import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { BacktestTradeView, ClosedTradeView } from "@/lib/types/models";
import { formatCurrency, formatDate } from "@/lib/utils";

type BacktestTradeEvidenceProps = {
  readonly fills: readonly BacktestTradeView[];
  readonly closedTrades: readonly ClosedTradeView[];
};

function ExecutionRows({ fills }: { readonly fills: readonly BacktestTradeView[] }) {
  if (fills.length === 0) return <p className="py-8 text-center text-sm text-muted-foreground">No fill-level executions were returned.</p>;
  return <>
    <div className="space-y-3 md:hidden">{fills.map((fill) => <article key={fill.order_id} className="space-y-2 rounded-lg border border-input p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-sm">{fill.ticker}</p><p className="text-xs text-muted-foreground">{formatDate(fill.timestamp)}</p></div><Badge variant="outline">{fill.side}</Badge></div><dl className="grid grid-cols-2 gap-2 text-xs"><div><dt className="text-muted-foreground">Quantity</dt><dd className="font-mono">{fill.quantity.toFixed(2)}</dd></div><div><dt className="text-muted-foreground">Fill price</dt><dd className="font-mono">{formatCurrency(fill.price)}</dd></div><div><dt className="text-muted-foreground">Fee</dt><dd className="font-mono">{formatCurrency(fill.fee)}</dd></div><div><dt className="text-muted-foreground">Slippage</dt><dd className="font-mono">{formatCurrency(fill.slippage)}</dd></div></dl></article>)}</div>
    <div className="hidden md:block"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Ticker</TableHead><TableHead>Side</TableHead><TableHead className="text-right">Quantity</TableHead><TableHead className="text-right">Fill price</TableHead><TableHead className="text-right">Fee</TableHead><TableHead className="text-right">Slippage</TableHead><TableHead className="text-right">Realized P/L</TableHead></TableRow></TableHeader><TableBody>{fills.map((fill) => <TableRow key={fill.order_id}><TableCell>{formatDate(fill.timestamp)}</TableCell><TableCell className="font-mono">{fill.ticker}</TableCell><TableCell><Badge variant="outline">{fill.side}</Badge></TableCell><TableCell className="text-right font-mono">{fill.quantity.toFixed(2)}</TableCell><TableCell className="text-right font-mono">{formatCurrency(fill.price)}</TableCell><TableCell className="text-right font-mono">{formatCurrency(fill.fee)}</TableCell><TableCell className="text-right font-mono">{formatCurrency(fill.slippage)}</TableCell><TableCell className="text-right font-mono">{formatCurrency(fill.realized_pnl)}</TableCell></TableRow>)}</TableBody></Table></div>
  </>;
}

function ClosedTradeRows({ closedTrades }: { readonly closedTrades: readonly ClosedTradeView[] }) {
  if (closedTrades.length === 0) return <p className="py-8 text-center text-sm text-muted-foreground">No closed round trips were returned. An open ending position is not a closed trade.</p>;
  return <>
    <div className="space-y-3 md:hidden">{closedTrades.map((trade) => <article key={`${trade.entry_at}-${trade.exit_at}-${trade.ticker}`} className="space-y-2 rounded-lg border border-input p-3"><div className="flex items-start justify-between gap-3"><p className="font-mono text-sm">{trade.ticker}</p><Badge variant="outline">{trade.holding_period_trading_days} trading days</Badge></div><dl className="grid grid-cols-2 gap-2 text-xs"><div><dt className="text-muted-foreground">Entry</dt><dd>{formatDate(trade.entry_at)} · {formatCurrency(trade.entry_vwap)}</dd></div><div><dt className="text-muted-foreground">Exit</dt><dd>{formatDate(trade.exit_at)} · {formatCurrency(trade.exit_vwap)}</dd></div><div><dt className="text-muted-foreground">Net realized P/L</dt><dd className="font-mono">{formatCurrency(trade.net_realized_pnl)}</dd></div><div><dt className="text-muted-foreground">Fees</dt><dd className="font-mono">{formatCurrency(trade.fees)}</dd></div><div><dt className="text-muted-foreground">Slippage</dt><dd className="font-mono">{formatCurrency(trade.slippage)}</dd></div></dl></article>)}</div>
    <div className="hidden md:block"><Table><TableHeader><TableRow><TableHead>Ticker</TableHead><TableHead>Entry</TableHead><TableHead>Exit</TableHead><TableHead className="text-right">Quantity</TableHead><TableHead className="text-right">Fees</TableHead><TableHead className="text-right">Slippage</TableHead><TableHead className="text-right">Net realized P/L</TableHead><TableHead className="text-right">Holding</TableHead></TableRow></TableHeader><TableBody>{closedTrades.map((trade) => <TableRow key={`${trade.entry_at}-${trade.exit_at}-${trade.ticker}`}><TableCell className="font-mono">{trade.ticker}</TableCell><TableCell>{formatDate(trade.entry_at)} · {formatCurrency(trade.entry_vwap)}</TableCell><TableCell>{formatDate(trade.exit_at)} · {formatCurrency(trade.exit_vwap)}</TableCell><TableCell className="text-right font-mono">{trade.quantity.toFixed(2)}</TableCell><TableCell className="text-right font-mono">{formatCurrency(trade.fees)}</TableCell><TableCell className="text-right font-mono">{formatCurrency(trade.slippage)}</TableCell><TableCell className="text-right font-mono">{formatCurrency(trade.net_realized_pnl)}</TableCell><TableCell className="text-right">{trade.holding_period_trading_days} days</TableCell></TableRow>)}</TableBody></Table></div>
  </>;
}

export function BacktestTradeEvidence({ fills, closedTrades }: BacktestTradeEvidenceProps) {
  return <div className="space-y-6"><Card><CardHeader><CardTitle className="text-base">Executions</CardTitle><CardDescription>Fill-level ledger events. Executions are not automatically closed round trips.</CardDescription></CardHeader><CardContent><ExecutionRows fills={fills} /></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Closed Trades</CardTitle><CardDescription>Round-trip economics after fees and slippage.</CardDescription></CardHeader><CardContent><ClosedTradeRows closedTrades={closedTrades} /></CardContent></Card></div>;
}
