from __future__ import annotations

from typing import Protocol

from broker.models import AccountSnapshot, Fill, Order, OrderStatus, Position


class BrokerGateway(Protocol):
    """Stable broker interface that later phases can swap for real execution."""

    def get_latest_price(self, ticker: str) -> float | None: ...

    def get_account(self) -> AccountSnapshot: ...

    def get_positions(self) -> list[Position]: ...

    def get_position(self, ticker: str) -> Position | None: ...

    def place_order(self, order: Order) -> Order: ...

    def cancel_order(self, order_id: str) -> Order: ...

    def get_order(self, order_id: str) -> Order | None: ...

    def get_orders(self, status: OrderStatus | None = None) -> list[Order]: ...

    def get_fills(self, order_id: str | None = None) -> list[Fill]: ...
